steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'docker/test/Dockerfile', '-t', 'redissample_test:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '-v', '/workspace:/redissample', 'redissample_test:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'docker/prebuild/Dockerfile', '-t', 'redissample_prebuild:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '-v', '/workspace:/redissample', 'redissample_prebuild:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/harai-kube-sandbox/redissample', '.']
images: ['asia.gcr.io/harai-kube-sandbox/redissample']
