#!/bin/bash -eu

docker-compose -p redissample -f docker-compose.test.yml build
docker-compose -p redissample -f docker-compose.test.yml up -d
docker-compose -p redissample -f docker-compose.test.yml exec redissample_test python test/test_app.py
docker-compose -p redissample -f docker-compose.prebuild.yml build
docker-compose -p redissample -f docker-compose.prebuild.yml up
docker build -t redissample:latest .
