#!/bin/bash -eu

docker-compose -p redissample -f docker-compose.prebuild.yml up --build
docker build -t redissample:latest .
docker-compose -p redissample -f docker-compose.test.yml up --build -d
docker-compose -p redissample -f docker-compose.test.yml exec redissample_test python test/test_app.py
